function  imageStruct = createImageStruct( conditionArray, ...
	binningArray, objectiveArray, redPathArray,yelPathArray )
%CREATE_IMAGE_STRUCT initializes empty structs for each localisation image
%   Defines all attributes of image struct and assigns initial data
%   to appropriate attributes.

pathN = length(redPathArray);
imageTemplate = struct(...
			'condition',''...
			,'redPath',''...
			,'yelPath',''...
			,'binning',[]...
			,'boundingBox',[] ...
			,'cellLocation',{{}}...
			,'redEntire',[]...
			,'redOutside',[]...
			,'yelEntire',[]...
			,'yelOutside',[]...
			,'yelMembrane',[]... 		
			,'yelMembraneAbsolute',[]...
      ,'yelEntireAbsolute',[]...
      ,'redEntireAbsolute',[]...
			,'redBackground',[]...
			,'yelBackground',[]...
			,'cellN',[] ...
			,'yelMembraneNeg',0 ...
			,'yelEntireNeg',0 ...
			,'redEntireNeg',0 ...
			,'deleteNeg',0);

imageStruct(1:pathN,1) = imageTemplate;

for i=1:pathN
	imageStruct(i).redPath			= redPathArray{i};
	imageStruct(i).yelPath			= yelPathArray{i};
	imageStruct(i).condition		= conditionArray{i};
	imageStruct(i).binning			= binningArray{i};
	imageStruct(i).objective		= objectiveArray{i};
end

end

